package:
  name: polysolver
  version: "1.0.0"

source:
  git_rev: master
  git_url: https://github.com/jason-weirather/polysolver.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - r-essentials
    - samtools
    - novoalign
    - strelka
    - mutect 1.1.4
    - java-jdk 7.*

about:
  home: https://github.com/jason-weirather/polysolver
  license: BSD
  license_file: LICENSE
