package:
  name: polysolver
  version: "1.0.0"

source:
  git_rev: master
  git_url: https://github.com/jason-weirather/hla-polysolver.git

build:
  number: 0

requirements:
  build:
    - python 2.7.*
    - setuptools
  run:
    - python 2.7.*
    - r-essentials
    - samtools
    - novoalign
    - strelka
    - mutect 1.1.*
    - java-jdk 7.*

about:
  home: https://github.com/jason-weirather/hla-polysolver
  license: BSD
  license_file: LICENSE
