package:
  name: hla-polysolver
  version: "1.0.0"

source:
  git_rev: master
  git_url: https://github.com/jason-weirather/hla-polysolver.git

build:
  number: 0

requirements:
  build:
    - python 2.7.*
    - perl 5.22.*
    - setuptools
    - perl-posix
    - perl-bioperl
    - perl-list-util
    - perl-list-moreutils
    - perl-parallel-forkmanager
    - perl-data-dumper
  run:
    - python 2.7.*
    - perl 5.22.*
    - r-essentials
    - samtools
    - novoalign
    - strelka
    - mutect 1.1.*
    - java-jdk 7.*
    - perl-posix
    - perl-bioperl
    - perl-list-util
    - perl-list-moreutils
    - perl-parallel-forkmanager
    - perl-data-dumper

about:
  home: https://github.com/jason-weirather/hla-polysolver
  license: BSD
  license_file: LICENSE
